In [17]:
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
data_dic = pd.read_csv("YRBS_2023_Data_Dictionary_Ordered.csv")

In [19]:
data_dic.head(20)

   Variable     Question_Description  Value            Value_Meaning
0        Q1          How old are you    1.0  12 years old or younger
1        Q1          How old are you    2.0             13 years old
2        Q1          How old are you    3.0             14 years old
3        Q1          How old are you    4.0             15 years old
4        Q1          How old are you    5.0             16 years old
5        Q1          How old are you    6.0             17 years old
6        Q1          How old are you    7.0    18 years old or older
7        Q2         What is your sex    1.0                   Female
8        Q2         What is your sex    2.0                     Male
9        Q3    In what grade are you    1.0                9th grade
10       Q3    In what grade are you    2.0               10th grade
11       Q3    In what grade are you    3.0               11th grade
12       Q3    In what grade are you    4.0               12th grade
13       Q3    In what grade are you    5.0  Ungraded or other grade
14       Q4  Are you Hispanic/Latino    1.0                      Yes
15       Q4  Are you Hispanic/Latino    2.0                       No
16       Q5        What is your race    NaN                      NaN
17       Q6         How tall are you    NaN                      NaN
18       Q7    How much do you weigh    NaN                      NaN
19       Q8            Seat belt use    1.0                    Never

In [20]:
raw_data = pd.read_csv('XXH2023_YRBS_Data.csv')
raw_data.head(5)

C:\Users\Acer\AppData\Local\Temp\ipykernel_3828\4010718000.py:1: DtypeWarning: Columns (0: Q92, 1: Q93, 2: Q94, 3: Q95, 4: Q96, 5: Q97, 6: Q98, 7: Q104, 8: Q105, 9: Q106, 10: Q107, 11: Q6ORIG) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('XXH2023_YRBS_Data.csv')

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,QNILLICT,QNOBESE,QNOWT,WEIGHT,STRATUM,PSU,BMIPCT,RACEETH,Q6ORIG,Q7ORIG
0,14 years old,Female,9th grade,NaN,C,1.65,81.65,Most of the time,4 or 5 times,Did not drive,...,NaN,1.0,2.0,0.8614,103,16294,97.08,NaN,505,180
1,15 years old,Male,9th grade,No,E,NaN,NaN,Always,0 times,Did not drive,...,2.0,NaN,NaN,0.8920,103,16294,NaN,White,N N,233
2,16 years old,Male,11th grade,No,E,1.68,74.84,Always,2 or 3 times,Did not drive when drinking,...,1.0,2.0,1.0,0.5081,103,16294,92.26,White,506,165
3,17 years old,Female,10th grade,No,E,NaN,NaN,Most of the time,0 times,Did not drive when drinking,...,1.0,NaN,NaN,1.1759,103,16294,NaN,White,N N,105
4,14 years old,Male,9th grade,No,E,1.85,56.70,Always,0 times,Did not drive,...,2.0,2.0,2.0,0.8920,103,16294,7.57,White,601,125

In [21]:
raw_data.columns

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
       ...
       'QNILLICT', 'QNOBESE', 'QNOWT', 'WEIGHT', 'STRATUM', 'PSU', 'BMIPCT',
       'RACEETH', 'Q6ORIG', 'Q7ORIG'],
      dtype='str', length=250)

In [22]:
selected_columns = ['Q1', 'Q2', 'Q3', 'Q9', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q20', 
                    'Q23', 'Q24', 'Q25', 'Q26', 'Q27', 'Q41', 'Q42', 'Q43', 'Q44', 'Q76', 
                    'Q80', 'Q84', 'Q85', 'Q86', 'Q87', 'Q89', 'Q90', 'Q91', 'Q100', 'Q101', 
                    'Q102', 'Q103', 'Q104', 'Q105', 'Q106']
data = raw_data[selected_columns]
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20103 entries, 0 to 20102
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Q1      20005 non-null  str
 1   Q2      19945 non-null  str
 2   Q3      19910 non-null  str
 3   Q9      19598 non-null  str
 4   Q14     18982 non-null  str
 5   Q15     17974 non-null  str
 6   Q16     11652 non-null  str
 7   Q17     17460 non-null  str
 8   Q18     14577 non-null  str
 9   Q20     15752 non-null  str
 10  Q23     18286 non-null  str
 11  Q24     19902 non-null  str
 12  Q25     19898 non-null  str
 13  Q26     19863 non-null  str
 14  Q27     19667 non-null  str
 15  Q41     19248 non-null  str
 16  Q42     19202 non-null  str
 17  Q43     15441 non-null  str
 18  Q44     14414 non-null  str
 19  Q76     18876 non-null  str
 20  Q80     15203 non-null  str
 21  Q84     15705 non-null  str
 22  Q85     17441 non-null  str
 23  Q86     14541 non-null  str
 24  Q87     16535 non-null  str
 25  Q89     13920 non-null  str
 26  Q90     13917 non-null  str
 27  Q91     13753 non-null  str
 28  Q100    13227 non-null  str
 29  Q101    13305 non-null  str
 30  Q102    13342 non-null  str
 31  Q103    11177 non-null  str
 32  Q104    10850 non-null  str
 33  Q105    10583 non-null  str
 34  Q106    10946 non-null  str
dtypes: str(35)
memory usage: 5.4 MB

In [23]:
data.columns = ['age', 'gender', 'education_level', 'ride_drinking_driver', 
                'school_safety_concern', 'threatened_at_school', 'fight_count', 
                'school_fight_count', 'neighborhood_violence', 'sexual_violence', 
                'school_racism', 'school_bullying', 'cyber_bullying', 'feel_hopeless', 
                'considered_suicide', 'first_alcohol', 'alcohol_frequency', 
                'hardcore_alcohol_frequency', 'drinking_in_a_row', 'exercise', 
                'social_media', 'mental_health', 'hours_of_sleep', 'sleep_place', 
                'grade', 'parent_emotional_abuse', 'parent_physical_abuse', 
                'parent_abuse_parent', 'parent_uses_alcohol', 'parent_mental_illness', 
                'incarcerated_parent', 'have_friend', 'parent_monitoring', 
                'unfair_discipline_school', 'ADHD']

In [24]:
data

,age,gender,education_level,ride_drinking_driver,school_safety_concern,threatened_at_school,fight_count,school_fight_count,neighborhood_violence,sexual_violence,...,parent_emotional_abuse,parent_physical_abuse,parent_abuse_parent,parent_uses_alcohol,parent_mental_illness,incarcerated_parent,have_friend,parent_monitoring,unfair_discipline_school,ADHD
0,14 years old,Female,9th grade,4 or 5 times,2 or 3 days,0 times,0 times,0 times,No,0 times,...,NaN,Never,Never,No,Yes,No,Not sure,Sometimes,No,No
1,15 years old,Male,9th grade,0 times,0 days,0 times,1 time,1 time,No,0 times,...,Rarely,Rarely,Rarely,No,No,No,Agree,Always,No,Yes
2,16 years old,Male,11th grade,2 or 3 times,0 days,0 times,0 times,0 times,No,0 times,...,Sometimes,Rarely,Rarely,No,No,Yes,Agree,Most of the time,No,No
3,17 years old,Female,10th grade,0 times,2 or 3 days,0 times,0 times,0 times,No,0 times,...,Never,Never,Never,No,No,No,Disagree,Always,No,Yes
4,14 years old,Male,9th grade,0 times,0 days,0 times,2 or 3 times,0 times,No,0 times,...,Never,Never,Never,No,No,No,Agree,Always,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20098,14 years old,Female,9th grade,0 times,0 days,1 time,NaN,0 times,No,1 time,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20099,15 years old,Male,9th grade,0 times,0 days,0 times,NaN,0 times,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20100,15 years old,Male,9th grade,0 times,0 days,0 times,NaN,0 times,No,0 times,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20101,16 years old,Male,9th grade,0 times,0 days,0 times,NaN,0 times,No,0 times,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20102,15 years old,Female,9th grade,0 times,0 days,0 times,NaN,0 times,No,0 times,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
data.isnull().sum()

age                             98
gender                         158
education_level                193
ride_drinking_driver           505
school_safety_concern         1121
threatened_at_school          2129
fight_count                   8451
school_fight_count            2643
neighborhood_violence         5526
sexual_violence               4351
school_racism                 1817
school_bullying                201
cyber_bullying                 205
feel_hopeless                  240
considered_suicide             436
first_alcohol                  855
alcohol_frequency              901
hardcore_alcohol_frequency    4662
drinking_in_a_row             5689
exercise                      1227
social_media                  4900
mental_health                 4398
hours_of_sleep                2662
sleep_place                   5562
grade                         3568
parent_emotional_abuse        6183
parent_physical_abuse         6186
parent_abuse_parent           6350
parent_uses_alcohol           6876
parent_mental_illness         6798
incarcerated_parent           6761
have_friend                   8926
parent_monitoring             9253
unfair_discipline_school      9520
ADHD                          9157
dtype: int64

In [26]:
# Mapping Values
drink_in_a_row = {
    'Did not drink in past 30 days': 1,
    '1 or 2 drinks': 2,
    '3 drinks': 3,
    '4 drinks': 4,
    '5 drinks': 5,
    '6 or 7 drinks': 6,
    '8 or 9 drinks': 7,
    '10 or more drinks': 8
}

exercise = {
    '0 days': 1,
    '1 day': 2, 
    '2 days': 3,
    '3 days': 4,
    '4 days': 5,
    '5 days': 6,
    '6 days': 7,
    '7 days': 8
}

social_media = {
    "I do not use social media": 1,
    "A few times a month": 2,
    "About once a week": 3,
    "A few times a week": 4,
    "About once a day": 5,
    "Several times a day": 6,
    "About once an hour": 7,
    "More than once an hour": 8
}

sleep_hours = {
    '4 or less hours': 1,
    '5 hours': 2,
    '6 hours': 3,
    '7 hours': 4,
    '8 hours': 5,
    '9 hours': 6,
    '10 or more hours': 7
}

housing = {
    'Home of parent or gaurdian': 1,
    'Home of other people': 2,
    'Shelter or emergency housing': 3,
    'Motel or hotel': 4,
    'Public place': 5,
    'No usual place': 6,
    'Somewhere else': 7
}

grades = {
    'Mostly A\'s': 1,
    'Mostly B\'s': 2,
    'Mostly C\'s': 3,
    'Mostly D\'s': 4,
    'Mostly F\'s': 5,
    'None of these grades': 6,
    'Not sure': 7
}

feel_close = {
    'Strongly agree': 1,
    'Agree': 2,
    'Not sure': 3,
    'Disagree': 4,
    'Strongly disagree': 5
}

frequency = {
    'Never': 1,
    'Rarely': 2,
    'Sometimes': 3,
    'Most of the time': 4,
    'Always': 5
}

yes_no = {
    'Yes': 1,
    'No': 2
}

data['drinking_in_a_row'] = data['drinking_in_a_row'].str.strip().map(drink_in_a_row)
data['exercise'] = data['exercise'].str.strip().map(exercise)
data['social_media'] = data['social_media'].str.strip().map(social_media)
data['mental_health'] = data['mental_health'].str.strip().map(frequency)
data['hours_of_sleep'] = data['hours_of_sleep'].str.strip().map(sleep_hours)
data['sleep_place'] = data['sleep_place'].str.strip().map(housing)
data['grade'] = data['grade'].str.strip().map(grades)
data['parent_emotional_abuse'] = data['parent_emotional_abuse'].str.strip().map(frequency)
data['parent_physical_abuse'] = data['parent_physical_abuse'].str.strip().map(frequency)
data['parent_abuse_parent'] = data['parent_abuse_parent'].str.strip().map(frequency)
data['parent_uses_alcohol'] = data['parent_uses_alcohol'].str.strip().map(yes_no)
data['parent_mental_illness'] = data['parent_mental_illness'].str.strip().map(yes_no)
data['incarcerated_parent'] = data['incarcerated_parent'].str.strip().map(yes_no)
data['have_friend'] = data['have_friend'].str.strip().map(feel_close)
data['parent_monitoring'] = data['parent_monitoring'].str.strip().map(frequency)
data['unfair_discipline_school'] = data['unfair_discipline_school'].str.strip().map(yes_no)
data['ADHD'] = data['ADHD'].str.strip().map(yes_no)

In [27]:
data['drinking_in_a_row'] = data['drinking_in_a_row'].fillna(data['drinking_in_a_row'].median())
data['exercise'] = data['exercise'].fillna(data['exercise'].median())
data['social_media'] = data['social_media'].fillna(data['social_media'].median())
data['mental_health'] = data['mental_health'].fillna(data['mental_health'].median())
data['hours_of_sleep'] = data['hours_of_sleep'].fillna(data['hours_of_sleep'].median())
data['sleep_place'] = data['sleep_place'].fillna(0) # 0 -> UNKNOWN
# keep only who has a grade info
data = data[~data['grade'].isin([6, 7])] # drop none grade and not sure
data = data.dropna(subset=['grade']) # drop students who do not have a grade info
data['parent_emotional_abuse'] = data['parent_emotional_abuse'].fillna(data['parent_emotional_abuse'].median())
data['parent_physical_abuse'] = data['parent_physical_abuse'].fillna(data['parent_physical_abuse'].median())
data['parent_abuse_parent'] = data['parent_abuse_parent'].fillna(data['parent_abuse_parent'].median())
data['parent_uses_alcohol'] = data['parent_uses_alcohol'].fillna(data['parent_uses_alcohol'].median())
data['parent_mental_illness'] = data['parent_mental_illness'].fillna(data['parent_mental_illness'].median())
data['incarcerated_parent'] = data['incarcerated_parent'].fillna(data['incarcerated_parent'].median())
data['have_friend'] = data['have_friend'].fillna(data['have_friend'].median())
data['parent_monitoring'] = data['parent_monitoring'].fillna(data['parent_monitoring'].median())
data['unfair_discipline_school'] = data['unfair_discipline_school'].fillna(data['unfair_discipline_school'].median())
data['ADHD'] = data['ADHD'].fillna(data['ADHD'].median())

In [28]:
data.info()

<class 'pandas.DataFrame'>
Index: 15694 entries, 1 to 20102
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         15624 non-null  str
 1   gender                      15596 non-null  str
 2   education_level             15575 non-null  str
 3   ride_drinking_driver        15252 non-null  str
 4   school_safety_concern       14722 non-null  str
 5   threatened_at_school        13757 non-null  str
 6   fight_count                 10362 non-null  str
 7   school_fight_count          13612 non-null  str
 8   neighborhood_violence       12864 non-null  str
 9   sexual_violence             13950 non-null  str
 10  school_racism               14172 non-null  str
 11  school_bullying             15592 non-null  str
 12  cyber_bullying              15572 non-null  str
 13  feel_hopeless               15560 non-null  str
 14  considered_suicide          15506 non-null  str
 15  first_alcohol               15255 non-null  str
 16  alcohol_frequency           15174 non-null  str
 17  hardcore_alcohol_frequency  11725 non-null  str
 18  drinking_in_a_row           15694 non-null  float64
 19  exercise                    15694 non-null  float64
 20  social_media                15694 non-null  float64
 21  mental_health               15694 non-null  float64
 22  hours_of_sleep              15694 non-null  float64
 23  sleep_place                 15694 non-null  float64
 24  grade                       15694 non-null  float64
 25  parent_emotional_abuse      15694 non-null  float64
 26  parent_physical_abuse       15694 non-null  float64
 27  parent_abuse_parent         15694 non-null  float64
 28  parent_uses_alcohol         15694 non-null  float64
 29  parent_mental_illness       15694 non-null  float64
 30  incarcerated_parent         15694 non-null  float64
 31  have_friend                 15694 non-null  float64
 32  parent_monitoring           15694 non-null  float64
 33  unfair_discipline_school    15694 non-null  float64
 34  ADHD                        15694 non-null  float64
dtypes: float64(17), str(18)
memory usage: 4.3 MB